language: clojure
jdk:
  - oraclejdk8
lein: lein2
script: lein2 do clean, compile, cljsbuild once, eastwood "{:exclude-namespaces [re-mote.zero.worker re-mote.zero.server re-mote.zero.common] }", cljfmt check
