version: '2'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.3"
    container_name: re-mote_elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
       - data:/usr/share/elasticsearch/data
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - cluster.name=re-ops
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
    networks: ['stack']


  kibana:
    image: "docker.elastic.co/kibana/kibana:5.6.3"
    container_name: re-mote_kibana
    environment: ['ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}']
    ports:
      - "5607:5601"
    networks: ['stack']
    depends_on: ['elasticsearch']
    environment:
      - XPACK_GRAPH_ENABLED=false
      - XPACK_MONITORING_ENABLED=false
      - XPACK_REPORTING_ENABLED=false
      - XPACK_SECURITY_ENABLED=false

  grafana:
    image: grafana/grafana:4.2.0
    container_name: re-mote/grafana
    ports:
      - "3000:3000"
    env_file:
      - './grafana/env.grafana'
    links:
      - elasticsearch
    networks: ['stack']

volumes:
    data:
      driver: local

networks: {stack: {}}
